name: Schedule
description: Schedule

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  cloud_firestore:
  flutter:
    sdk: flutter
  flutter_advanced_networkimage:
  cupertino_icons: ^0.1.2
  cached_network_image: ^0.7.0
  flutter_svg: ^0.12.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.2"

flutter_icons:
  image_path: "assets/images/new1.png" 
  android: true
  ios: true


flutter:

  uses-material-design: true

  assets:
    - assets/images/new.svg
    - assets/images/runningMan.svg
    - assets/images/cric-bat.svg
    - assets/images/hockey.svg
    - assets/images/burger.svg
    - assets/images/ice_cream.svg

  fonts:
    - family: Qwigley
      fonts:
        - asset: assets/fonts/qwigley/Qwigley-Regular.ttf
    - family: Dosis
      fonts:
        - asset: assets/fonts/dosis/Dosis-Regular.otf
          weight: 400
        - asset: assets/fonts/dosis/Dosis-Medium.otf
          weight: 500
        - asset: assets/fonts/dosis/Dosis-SemiBold.otf
          weight: 600
        - asset: assets/fonts/dosis/Dosis-Bold.otf
          weight: 800
        - asset: assets/fonts/dosis/Dosis-ExtraBold.otf
          weight: 900